export const AppMode = {
  CHAT: 'CHAT',
  LIVE: 'LIVE',
  IMAGES: 'IMAGES',
  VISION: 'VISION',
  FAST: 'FAST',
  CODING: 'CODING',
  VIDEO: 'VIDEO'
};

export const ImageResolution = {
  RES_1K: '1K',
  RES_2K: '2K',
  RES_4K: '4K'
};

export const SYSTEM_LITERALS = "YOU MUST RESPOND USING ONLY ALPHABETIC CHARACTERS AND SPACES. DO NOT USE PUNCTUATION LIKE COLONS HYPHENS SLASHES PARENTHESES OR QUOTES. THE ONLY EXCEPTION IS DURING MATH CALCULATIONS WHERE YOU MAY USE PLUS MINUS MULTIPLY DIVIDE AND EQUALS SYMBOLS. OTHERWISE USE ONLY LETTERS.";